"""

Revision ID: 4014b50cab9d
Revises: 9b46ff543492
Create Date: 2019-12-13 17:40:56.732398

"""

# revision identifiers, used by Alembic.
revision = '4014b50cab9d'
down_revision = '9b46ff543492'

from alembic import op
import sqlalchemy as sa


def upgrade():
    op.drop_index('id', table_name='clients')
    op.drop_index('affiliation_action_id', table_name='affiliation_actions')
    op.drop_index('affiliation_id', table_name='affiliations')
    op.drop_index('agreement_id', table_name='agreements')
    op.drop_index('ix_analytics_datestr', table_name='analytics')
    op.drop_index('analytic_id', table_name='analytics_firmware')
    op.drop_index('analytic_id', table_name='analytics_vendor')
    op.drop_index('category_id', table_name='categories')
    op.drop_index('certificate_id', table_name='certificates')
    op.drop_index('checksum_id', table_name='checksums')
    op.drop_index('ix_component_claims_component_claim_id', table_name='component_claims')
    op.drop_index('ix_component_issues_component_issue_id', table_name='component_issues')
    op.drop_index('ix_component_refs_component_ref_id', table_name='component_refs')
    op.drop_index('component_shard_certificate_id', table_name='component_shard_certificates')
    op.drop_index('checksum_id', table_name='component_shard_checksums')
    op.drop_index('component_shard_info_id', table_name='component_shard_infos')
    op.drop_index('component_shard_id', table_name='component_shards')
    op.drop_index('ix_components_component_id', table_name='components')
    op.drop_index('condition_id', table_name='conditions')
    op.drop_index('id', table_name='event_log')
    op.drop_index('ix_firmware_firmware_id', table_name='firmware')
    op.drop_index('firmware_event_id', table_name='firmware_events')
    op.drop_index('firmware_limit_id', table_name='firmware_limits')
    op.drop_index('guid_id', table_name='guids')
    op.drop_index('issue_id', table_name='issues')
    op.drop_index('keyword_id', table_name='keywords')
    op.drop_index('namespace_id', table_name='namespaces')
    op.drop_index('protocol_id', table_name='protocol')
    op.drop_index('remote_id', table_name='remotes')
    op.drop_index('report_attribute_id', table_name='report_attributes')
    op.drop_index('id', table_name='reports')
    op.drop_index('requirement_id', table_name='requirements')
    op.drop_index('restriction_id', table_name='restrictions')
    op.drop_index('search_event_id', table_name='search_events')
    op.drop_index('setting_id', table_name='settings')
    op.drop_index('test_attribute_id', table_name='test_attributes')
    op.drop_index('test_id', table_name='tests')
    op.drop_index('user_action_id', table_name='user_actions')
    op.drop_index('condition_id', table_name='useragents')
    op.drop_index('user_id', table_name='users')
    op.drop_index('vendor_id', table_name='vendors')
    op.drop_index('verfmt_id', table_name='verfmts')
    op.drop_index('yara_query_id', table_name='yara_query')
    op.drop_index('yara_query_result_id', table_name='yara_query_result')

def downgrade():
    op.create_index('yara_query_result_id', 'yara_query_result', ['yara_query_result_id'], unique=True)
    op.create_index('yara_query_id', 'yara_query', ['yara_query_id'], unique=True)
    op.create_index('verfmt_id', 'verfmts', ['verfmt_id'], unique=True)
    op.create_index('vendor_id', 'vendors', ['vendor_id'], unique=True)
    op.create_index('user_id', 'users', ['user_id'], unique=True)
    op.create_index('condition_id', 'useragents', ['useragent_id'], unique=True)
    op.create_index('user_action_id', 'user_actions', ['user_action_id'], unique=True)
    op.create_index('test_id', 'tests', ['test_id'], unique=True)
    op.create_index('test_attribute_id', 'test_attributes', ['test_attribute_id'], unique=True)
    op.create_index('setting_id', 'settings', ['setting_id'], unique=True)
    op.create_index('search_event_id', 'search_events', ['search_event_id'], unique=True)
    op.create_index('restriction_id', 'restrictions', ['restriction_id'], unique=True)
    op.create_index('requirement_id', 'requirements', ['requirement_id'], unique=True)
    op.create_index('id', 'reports', ['report_id'], unique=True)
    op.create_index('report_attribute_id', 'report_attributes', ['report_attribute_id'], unique=True)
    op.create_index('remote_id', 'remotes', ['remote_id'], unique=True)
    op.create_index('protocol_id', 'protocol', ['protocol_id'], unique=True)
    op.create_index('namespace_id', 'namespaces', ['namespace_id'], unique=True)
    op.create_index('keyword_id', 'keywords', ['keyword_id'], unique=True)
    op.create_index('issue_id', 'issues', ['issue_id'], unique=True)
    op.create_index('guid_id', 'guids', ['guid_id'], unique=True)
    op.create_index('firmware_limit_id', 'firmware_limits', ['firmware_limit_id'], unique=True)
    op.create_index('firmware_event_id', 'firmware_events', ['firmware_event_id'], unique=True)
    op.create_index('ix_firmware_firmware_id', 'firmware', ['firmware_id'], unique=True)
    op.create_index('id', 'event_log', ['id'], unique=True)
    op.create_index('condition_id', 'conditions', ['condition_id'], unique=True)
    op.create_index('ix_components_component_id', 'components', ['component_id'], unique=True)
    op.create_index('component_shard_id', 'component_shards', ['component_shard_id'], unique=True)
    op.create_index('component_shard_info_id', 'component_shard_infos', ['component_shard_info_id'], unique=True)
    op.create_index('checksum_id', 'component_shard_checksums', ['checksum_id'], unique=True)
    op.create_index('component_shard_certificate_id', 'component_shard_certificates', ['component_shard_certificate_id'], unique=True)
    op.create_index('ix_component_refs_component_ref_id', 'component_refs', ['component_ref_id'], unique=True)
    op.create_index('ix_component_issues_component_issue_id', 'component_issues', ['component_issue_id'], unique=True)
    op.create_index('ix_component_claims_component_claim_id', 'component_claims', ['component_claim_id'], unique=True)
    op.create_index('id', 'clients', ['id'], unique=True)
    op.create_index('checksum_id', 'checksums', ['checksum_id'], unique=True)
    op.create_index('certificate_id', 'certificates', ['certificate_id'], unique=True)
    op.create_index('category_id', 'categories', ['category_id'], unique=True)
    op.create_index('analytic_id', 'analytics_vendor', ['analytic_id'], unique=True)
    op.create_index('analytic_id', 'analytics_firmware', ['analytic_id'], unique=True)
    op.create_index('ix_analytics_datestr', 'analytics', ['datestr'], unique=True)
    op.create_index('agreement_id', 'agreements', ['agreement_id'], unique=True)
    op.create_index('affiliation_id', 'affiliations', ['affiliation_id'], unique=True)
    op.create_index('affiliation_action_id', 'affiliation_actions', ['affiliation_action_id'], unique=True)
