"""

Revision ID: e1b495a29979
Revises: 79020880db98
Create Date: 2020-01-17 08:59:07.418661

"""

# revision identifiers, used by Alembic.
revision = 'e1b495a29979'
down_revision = '79020880db98'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_affiliation_actions_affiliation_id'), 'affiliation_actions', ['affiliation_id'], unique=False)
    op.create_index(op.f('ix_affiliations_vendor_id'), 'affiliations', ['vendor_id'], unique=False)
    op.create_index(op.f('ix_affiliations_vendor_id_odm'), 'affiliations', ['vendor_id_odm'], unique=False)
    op.create_index(op.f('ix_certificates_user_id'), 'certificates', ['user_id'], unique=False)
    op.create_index(op.f('ix_checksums_component_id'), 'checksums', ['component_id'], unique=False)
    op.create_index(op.f('ix_component_claims_component_id'), 'component_claims', ['component_id'], unique=False)
    op.create_index(op.f('ix_component_issues_component_id'), 'component_issues', ['component_id'], unique=False)
    op.create_index(op.f('ix_component_refs_component_id'), 'component_refs', ['component_id'], unique=False)
    op.create_index(op.f('ix_component_refs_vendor_id'), 'component_refs', ['vendor_id'], unique=False)
    op.create_index(op.f('ix_component_refs_vendor_id_partner'), 'component_refs', ['vendor_id_partner'], unique=False)
    op.create_index(op.f('ix_component_shard_certificates_component_shard_id'), 'component_shard_certificates', ['component_shard_id'], unique=False)
    op.create_index(op.f('ix_component_shard_checksums_component_shard_id'), 'component_shard_checksums', ['component_shard_id'], unique=False)
    op.create_index(op.f('ix_component_shards_component_id'), 'component_shards', ['component_id'], unique=False)
    op.create_index(op.f('ix_conditions_issue_id'), 'conditions', ['issue_id'], unique=False)
    op.create_index(op.f('ix_event_log_user_id'), 'event_log', ['user_id'], unique=False)
    op.create_index(op.f('ix_event_log_vendor_id'), 'event_log', ['vendor_id'], unique=False)
    op.create_index(op.f('ix_firmware_remote_id'), 'firmware', ['remote_id'], unique=False)
    op.create_index(op.f('ix_firmware_user_id'), 'firmware', ['user_id'], unique=False)
    op.create_index(op.f('ix_firmware_vendor_id'), 'firmware', ['vendor_id'], unique=False)
    op.create_index(op.f('ix_firmware_events_firmware_id'), 'firmware_events', ['firmware_id'], unique=False)
    op.create_index(op.f('ix_firmware_limits_firmware_id'), 'firmware_limits', ['firmware_id'], unique=False)
    op.create_index(op.f('ix_guids_component_id'), 'guids', ['component_id'], unique=False)
    op.create_index(op.f('ix_keywords_component_id'), 'keywords', ['component_id'], unique=False)
    op.create_index(op.f('ix_namespaces_vendor_id'), 'namespaces', ['vendor_id'], unique=False)
    op.create_index(op.f('ix_report_attributes_report_id'), 'report_attributes', ['report_id'], unique=False)
    op.create_index(op.f('ix_requirements_component_id'), 'requirements', ['component_id'], unique=False)
    op.create_index(op.f('ix_restrictions_vendor_id'), 'restrictions', ['vendor_id'], unique=False)
    op.create_index(op.f('ix_test_attributes_test_id'), 'test_attributes', ['test_id'], unique=False)
    op.create_index(op.f('ix_tests_firmware_id'), 'tests', ['firmware_id'], unique=False)
    op.create_index(op.f('ix_user_actions_user_id'), 'user_actions', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_vendor_id'), 'users', ['vendor_id'], unique=False)
    op.create_index(op.f('ix_yara_query_user_id'), 'yara_query', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_yara_query_user_id'), table_name='yara_query')
    op.drop_index(op.f('ix_users_vendor_id'), table_name='users')
    op.drop_index(op.f('ix_user_actions_user_id'), table_name='user_actions')
    op.drop_index(op.f('ix_tests_firmware_id'), table_name='tests')
    op.drop_index(op.f('ix_test_attributes_test_id'), table_name='test_attributes')
    op.drop_index(op.f('ix_restrictions_vendor_id'), table_name='restrictions')
    op.drop_index(op.f('ix_requirements_component_id'), table_name='requirements')
    op.drop_index(op.f('ix_report_attributes_report_id'), table_name='report_attributes')
    op.drop_index(op.f('ix_namespaces_vendor_id'), table_name='namespaces')
    op.drop_index(op.f('ix_keywords_component_id'), table_name='keywords')
    op.drop_index(op.f('ix_guids_component_id'), table_name='guids')
    op.drop_index(op.f('ix_firmware_limits_firmware_id'), table_name='firmware_limits')
    op.drop_index(op.f('ix_firmware_events_firmware_id'), table_name='firmware_events')
    op.drop_index(op.f('ix_firmware_vendor_id'), table_name='firmware')
    op.drop_index(op.f('ix_firmware_user_id'), table_name='firmware')
    op.drop_index(op.f('ix_firmware_remote_id'), table_name='firmware')
    op.drop_index(op.f('ix_event_log_vendor_id'), table_name='event_log')
    op.drop_index(op.f('ix_event_log_user_id'), table_name='event_log')
    op.drop_index(op.f('ix_conditions_issue_id'), table_name='conditions')
    op.drop_index(op.f('ix_component_shards_component_id'), table_name='component_shards')
    op.drop_index(op.f('ix_component_shard_checksums_component_shard_id'), table_name='component_shard_checksums')
    op.drop_index(op.f('ix_component_shard_certificates_component_shard_id'), table_name='component_shard_certificates')
    op.drop_index(op.f('ix_component_refs_vendor_id_partner'), table_name='component_refs')
    op.drop_index(op.f('ix_component_refs_vendor_id'), table_name='component_refs')
    op.drop_index(op.f('ix_component_refs_component_id'), table_name='component_refs')
    op.drop_index(op.f('ix_component_issues_component_id'), table_name='component_issues')
    op.drop_index(op.f('ix_component_claims_component_id'), table_name='component_claims')
    op.drop_index(op.f('ix_checksums_component_id'), table_name='checksums')
    op.drop_index(op.f('ix_certificates_user_id'), table_name='certificates')
    op.drop_index(op.f('ix_affiliations_vendor_id_odm'), table_name='affiliations')
    op.drop_index(op.f('ix_affiliations_vendor_id'), table_name='affiliations')
    op.drop_index(op.f('ix_affiliation_actions_affiliation_id'), table_name='affiliation_actions')
    # ### end Alembic commands ###
